version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis
    ports:
      - "6379:6379"
    labels:
      - "name=redis"
      - "mode=standalone"
  php:
    build:
      context: ./php
      dockerfile: ./Dockerfile
    container_name: php
    ports:
      - "9000:9000"
